/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SstadminRouteImport } from './routes/sstadmin'
import { Route as Sstadmin_dashboardRouteImport } from './routes/sstadmin_dashboard'
import { Route as WorkshopsRouteImport } from './routes/workshops'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SstadminRoute = SstadminRouteImport.update({
  id: '/sstadmin',
  path: '/sstadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const Sstadmin_dashboardRoute = Sstadmin_dashboardRouteImport.update({
  id: '/sstadmin_dashboard',
  path: '/sstadmin_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sstadmin': typeof SstadminRoute
  '/sstadmin_dashboard': typeof Sstadmin_dashboardRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sstadmin': typeof SstadminRoute
  '/sstadmin_dashboard': typeof Sstadmin_dashboardRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sstadmin': typeof SstadminRoute
  '/sstadmin_dashboard': typeof Sstadmin_dashboardRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sstadmin' | '/sstadmin_dashboard' | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sstadmin' | '/sstadmin_dashboard' | '/workshops'
  id: '__root__' | '/' | '/sstadmin' | '/sstadmin_dashboard' | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SstadminRoute: typeof SstadminRoute
  Sstadmin_dashboardRoute: typeof Sstadmin_dashboardRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sstadmin': {
      id: '/sstadmin'
      path: '/sstadmin'
      fullPath: '/sstadmin'
      preLoaderRoute: typeof SstadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sstadmin_dashboard': {
      id: '/sstadmin_dashboard'
      path: '/sstadmin_dashboard'
      fullPath: '/sstadmin_dashboard'
      preLoaderRoute: typeof Sstadmin_dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SstadminRoute: SstadminRoute,
  Sstadmin_dashboardRoute: Sstadmin_dashboardRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
